### ISSUE TITLE
quest (55)brother's in death

### ISSUE THREAD

**Issue by project58** [blackfrost-server/BlackFrost-Server#13]
quest (55) Brother's in death

##### SMALL DESCRIPTION: npc of the quest does not appear
npc of the quest does not appear

##### STEPS TO REPRODUCE THE PROBLEM:
npc Koltira does not appear

1. 
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/f1b44029c85b9e25318ba84a099b4103e0d98f4e

**Comment by Si1ker** [comment]
@project58 Thanks for your report however this report is incomplete and is not using the complete issue template.
