### ISSUE TITLE
(Suggestion) Endgame resources are way too hard to find

### ISSUE THREAD

**Issue by OhmTheWise** [blackfrost-server/BlackFrost-Server#2]
This is more of a suggestion than a bug report:

Mining and Herbalism deposits in Northrend are extremely rare, maybe 'cause the server's playerbase is growing every day, still titanium and stuff are hard to find and their respwan rate takes too long, making the gathering of said resources basically impossible.

If there's anything that can be done about it, i know for sure that wouls make a lotta players happy.

Thanks, for the patience, I hope I'm doing this right.

f1b44029c85b9e25318ba84a099b4103e0d98f4e

**Comment by Si1ker** [comment]
@OhmTheWise Hello !

There are some phases in some parts of Northrend that could hide some resources, this would eventually improve changing from patch to patch until we get to the end game content.
Also, I recommend you to visit this cave which has a lot of titanium and saronite:

![image](https://user-images.githubusercontent.com/61223313/83827235-0c04bc00-a69b-11ea-88b8-aa8e60e76080.png)
![image](https://user-images.githubusercontent.com/61223313/83827281-25a60380-a69b-11ea-9d4a-1f5de10bf892.png)

Thanks for the time on the suggestion, we appreciate that a lot !
