### ISSUE TITLE
(BUG) Varios fallos Sagrario de Obsidiana 10j. 

### ISSUE THREAD

**Issue by Veesha-The-Monkey** [blackfrost-server/BlackFrost-Server#8]
Bugs varios en Sagrario Obsiana 10j

##### SMALL DESCRIPTION:

1. El lugar donde aparece Fisura de las Sombras no coincide con el lugar donde realiza el daño. (Desfase visual)
2. Al entrar al portal de cualquier dragón, Sartharion sigue lanzando Pyrobuffet/Pirosacudida dentro de esta fase.
3. **A veces**, al matar a Shadron, o en cualquier momento del combate el portal de este desaparece y deja el buff sobre Sartharion.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. Debería hacer el daño **en el mismo lugar** donde aparece Fisura de las Sombras.
2. Al entrar a cualquier portal Sartharion **no debería tirar** Pyrobuffet/Pirosacudida dentro de esta fase.
3. El portal **no debería desaparecer**, al entrar y matar los adds, debería quitarle el buff "Ofrenda del Crepúsculo" a Sartharion.

##### CURRENT BEHAVIOUR:

1.  El lugar donde aparece Fisura de las Sombras no coincide con el lugar donde realiza el daño, este puede salir de manera aleatoria en cualquier lugar, afectando el desarrollo con normalidad del evento. Aclaración: esta spell es lanzada por cualquiera de los tres dragones morados (Shadron, Vesperon, Tenebron).
       -Ejemplo  https://www.youtube.com/watch?v=HZlyuKuBl8I al segundo 0:45 se puede ver el funcionamiento correcto de esta habilidad.

2. Al entrar a cualquier portal, en cualquier momento del encuentro Sartharion no debería tirar https://es.wowhead.com/spell=57557/pirosacudida dentro de esta fase. Esto solo ocurre cuando fuera de los portales, te alejas de Sartharion, entonces el te lanzará esta spell. 
3. Durante el encuentro, cualquiera de los tres dragones morados mencionados anteriormente lanzarán portales. El portal de Shadron funciona de la siguiente manera.
      - Portal de Shadron: Este portal perdura todo el encuentro con acólitos que invoca cada 30s. sólo desaparece cuando matas a los acólitos dentro, o sea que puedes matar a Shadron y el portal seguiría existiendo. / En Blackfrost el portal **desaparece** sin siquiera poder entrar y Sartharion queda con el buff Ofrenda del Crepúsculo por lo cual se hace imposible matarlo.
       -Ejemplo del funcionamiento correcto de estos dos errores: https://www.youtube.com/watch?v=uZe9-yc0s7A es 25j. pero la mecánica es la misma en ambas modalidades. A partir del minuto 1:17 se puede ver morir a Shadron, entrar al portal, matar los add sin Pirosacudida, se quita el Buff a Sartharion y el encuentro sigue con normalidad. 

PD: Estoy usando links a wowhead porque la base de datos proporcionada en esta plantilla no tiene datos sobre los hechizos que menciono.
##### STEPS TO REPRODUCE THE PROBLEM:

1. Entrar a la banda Sagrario Obsidiana en modo 10j.
2.  Dejar al menos a Shadron y Tenebron vivos, o Shadron y otro dragón.
3. Reproducir el encuentro con normalidad. Matar a Shadron antes que a Sartharion, si no desaparece el portal, entrar en él para comprobar el fallo del hechizo Pirosacudida. 
4. Dejar que desaparezca el portal, sin matar al acólito dentro para comprobar el fallo del funcionamiento de este portal, que deja activo el buff Ofrenda del Crepúsculo.
5. Comprobar la presencia del buff Ofrenda de Crepúsculo sobre Sartharion. 

Gracias. 

Bug reportado por Aguusmza
##### AC HASH/COMMIT:
 f1b44029c85b9e25318ba84a099b4103e0d98f4e

**Comment by Si1ker** [comment]
Will continue on #3
